// Reads public/music/album-covers.json — the flat set of album codes that have a
// real published cover on the CDN (generated by scripts/gen-album-covers.mjs by
// probing the CDN). The web layer (lib/covers.ts) uses the same file to show only
// albums that actually have artwork; the API never loaded it until hero auto-rotate
// needed the "has a cover image" eligibility check server-side.
//
// mtime-cached (reloads when the file changes), matching util/coverVersions.js.
import fs from 'node:fs';
import path from 'node:path';
import { config } from '../config.js';

const FILE = path.join(path.dirname(config.manifestPath), 'album-covers.json');

let cache = { set: new Set(), mtime: -1 };
function load() {
  try {
    const st = fs.statSync(FILE);
    if (st.mtimeMs !== cache.mtime) {
      const data = JSON.parse(fs.readFileSync(FILE, 'utf8'));
      cache = { set: new Set(Array.isArray(data.covers) ? data.covers : []), mtime: st.mtimeMs };
    }
  } catch { /* no file yet — treat as "no covers" */ }
  return cache.set;
}

// True when the album has a published cover on the CDN (case-insensitive on code).
export function hasCover(code) {
  return load().has(String(code || '').toUpperCase());
}
