import fs from 'node:fs';
import path from 'node:path';
import { getBackstagePiece } from '@/lib/backstage';

// Serves a Backstage card/hero image from disk at request time.
//
// Why a route instead of the static public URL: `next start` only serves files
// that were in public/ AT BUILD TIME. An image regenerated by the Image Studio
// afterwards is a new file, so /images/backstage/<slug>.webp 404s until a
// rebuild. Reading it here (Node runtime, per request) makes regenerated images
// appear immediately. The content-type is sniffed from the bytes, so a file
// saved with a .webp name that is actually PNG/JPEG still serves correctly.

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

const PUBLIC_DIR = path.join(process.cwd(), 'public');
const SLUG_RE = /^[a-z0-9][a-z0-9-]{0,120}$/;

function sniff(buf: Buffer): string {
  if (buf.length >= 4 && buf[0] === 0x89 && buf[1] === 0x50 && buf[2] === 0x4e && buf[3] === 0x47) return 'image/png';
  if (buf.length >= 3 && buf[0] === 0xff && buf[1] === 0xd8 && buf[2] === 0xff) return 'image/jpeg';
  if (buf.length >= 12 && buf.toString('ascii', 0, 4) === 'RIFF' && buf.toString('ascii', 8, 12) === 'WEBP') return 'image/webp';
  return 'application/octet-stream';
}

export async function GET(_req: Request, { params }: { params: { slug: string } }) {
  const slug = params.slug || '';
  if (!SLUG_RE.test(slug)) return new Response('Bad request', { status: 400 });

  const piece = getBackstagePiece(slug);
  const rel = piece?.image; // raw path from backstage.json, e.g. /images/backstage/<slug>.webp
  if (!rel) return new Response('Not found', { status: 404 });

  const file = path.join(PUBLIC_DIR, rel.replace(/^\/+/, '').split('?')[0]);
  // Path-traversal guard: the resolved file must stay under public/.
  if (!file.startsWith(PUBLIC_DIR)) return new Response('Bad request', { status: 400 });

  try {
    const buf = await fs.promises.readFile(file);
    return new Response(new Uint8Array(buf), {
      headers: {
        'Content-Type': sniff(buf),
        // The URL carries ?v=<mtime>, so a regenerated file gets a new URL and
        // this copy can be cached hard by the browser.
        'Cache-Control': 'public, max-age=31536000, immutable',
      },
    });
  } catch {
    return new Response('Not found', { status: 404 });
  }
}
