// ============================================================================
// Album cover sourcing. Covers live on the CDN at:
//   <CDN>/music/<album.path>/artwork/<CODE>.png
//
// `album-covers.json` (generated by scripts/gen-album-covers.mjs by probing the
// CDN) records which albums actually have a published cover there. We use it to
// (a) link covers directly to the CDN when present, and (b) let the Home page
// show only albums that have a real cover.
//
// Server-only (reads the generated file via fs). Import from Server Components.
// ============================================================================
import fs from 'node:fs';
import path from 'node:path';

const CDN = (process.env.NEXT_PUBLIC_CDN_BASE || 'https://cdn.jubileeverse.com').replace(/\/$/, '');

// Direct CDN url for an album's published cover art (cache-busted when replaced).
export function cdnCoverUrl(code: string, albumPath: string): string {
  return withVersion(`${CDN}/music/${albumPath}/artwork/${code}.png`, code);
}

let coverSet: Set<string> | null = null;
function load(): Set<string> {
  if (coverSet) return coverSet;
  try {
    const file = path.join(process.cwd(), 'public', 'music', 'album-covers.json');
    const data = JSON.parse(fs.readFileSync(file, 'utf8'));
    coverSet = new Set<string>(Array.isArray(data.covers) ? data.covers : []);
  } catch {
    coverSet = new Set<string>();
  }
  return coverSet;
}

// Cache-bust versions for admin-replaced covers ({ CODE: version }); appended as
// ?v=<version> so a new cover shows past the 1-year immutable CDN cache. Reloaded
// when cover-versions.json changes (written by the API on each cover upload).
let verCache: { v: Record<string, number>; mtime: number } = { v: {}, mtime: 0 };
function coverVersion(code: string): number {
  try {
    const file = path.join(process.cwd(), 'public', 'music', 'cover-versions.json');
    const st = fs.statSync(file);
    if (st.mtimeMs !== verCache.mtime) {
      verCache = { v: JSON.parse(fs.readFileSync(file, 'utf8')).versions || {}, mtime: st.mtimeMs };
    }
  } catch { /* no file yet */ }
  return verCache.v[code.toUpperCase()] || 0;
}
const withVersion = (url: string, code: string): string => {
  const v = coverVersion(code);
  return v ? `${url}${url.includes('?') ? '&' : '?'}v=${v}` : url;
};

// True when the album has a published cover on the CDN.
export function hasCover(code: string): boolean {
  return load().has(code);
}

// Best cover url for an album: the direct CDN url when the cover is published
// there, otherwise the CDN-first /cover route (which falls back to local art).
// Returns '' when the album has no folder at all.
export function coverFor(code: string, albumPath?: string | null): string {
  if (!albumPath) return '';
  return hasCover(code) ? cdnCoverUrl(code, albumPath) : withVersion(`/cover/${code}.png`, code);
}
