// ============================================================================
// Album SUPPORT images.
//
// A supporting image is the wide 16:9 band that sits above an album's song
// list. It is not the cover: it is a second photograph derived FROM the cover —
// same person, same place, same light, opened out — generated by the WPF Studio
// (wpf/SupportImages.cs) and stored beside the cover master:
//
//   <album>/artwork/<CODE>-support-<N>.webp                      music drive
//   <CDN>/music/<album.path>/artwork/<CODE>-support-<N>.webp      once pushed
//
// WHY THERE IS A NUMBER IN THE NAME, AND WHY THIS FILE CARES.
// The Studio generates several drafts per album and writes them all, numbered.
// Choosing between them is done by DELETING the ones you do not want, and the
// LOWEST-NUMBERED SURVIVOR is the album's image. That rule lives in exactly two
// places — the probe script that writes album-support.json, and the Studio that
// names the files — and the probe resolves it against what is actually on the
// CDN rather than assuming draft 1 survived.
//
// WHAT THE JSON IS FOR, NOW THAT THE ROUTE RESOLVES THE URL: it is purely an
// EXISTENCE INDEX — "does this album have a supporting image at all". That
// question has to be answered synchronously while the hero renders, and neither
// a CDN probe nor a disk walk can happen there. Generate it with
// scripts/gen-album-support.mjs: default mode probes the CDN (what a production
// deploy needs), `--local` scans the music drive (what the studio machine needs
// to see its own freshly generated work).
//
// KEYED BY CODE, AND HOLDING THE WHOLE SUBPATH. Deliberately unlike
// lib/covers.ts, which takes an albumPath alongside the code. The album page
// switches albums in place from a rail whose entries carry a code and no path
// (see getArtist in lib/manifest.ts), so a path-taking signature would have
// forced either an O(n²) manifest lookup per page or a band that appears for
// the first album only. The probe already holds the manifest; it writes the
// subpath it resolved, and nothing downstream has to rediscover it.
//
// Server-only (reads the generated file via fs). Import from Server Components.
// ============================================================================
import fs from 'node:fs';
import path from 'node:path';

// { CODE: "<album.path>/artwork/<CODE>-support-<N>.webp" }. Loaded once per
// process, like the cover set.
let supportMap: Record<string, string> | null = null;
function load(): Record<string, string> {
  if (supportMap) return supportMap;
  try {
    const file = path.join(process.cwd(), 'public', 'music', 'album-support.json');
    const data = JSON.parse(fs.readFileSync(file, 'utf8'));
    supportMap = (data && typeof data.support === 'object' && data.support) || {};
  } catch {
    // No file yet is the normal state until the first probe runs. An album page
    // without a supporting image is a complete page, so this is not an error.
    supportMap = {};
  }
  return supportMap!;
}

/** True when this album has a supporting image published on the CDN. */
export function hasSupportImage(code: string): boolean {
  return !!load()[code.toUpperCase()];
}

/**
 * The supporting image url for an album, or '' when it has none.
 *
 * RESOLVED THROUGH /support/<code>.webp, NOT AS A DIRECT CDN URL, and that is
 * the fix for the whole class of "it does not work yet" here. A direct url has
 * to name one specific place and one specific draft number, and both of those
 * change: the picture is written to the music drive first and reaches the CDN
 * later, and which draft survives depends on which ones were deleted. The route
 * tries the CDN, then the drive, and re-resolves the draft on its own — so an
 * image shows the moment it exists, and keeps showing after it is synced.
 *
 * Covers already work exactly this way (`coverFor` falls back to /cover/<code>),
 * so this is the house pattern rather than a new one.
 *
 * Returns '' when the album has no supporting image at all, which is what lets
 * the album hero fall back to its persona banner. Never return a route url on a
 * guess: a background-image that 404s paints nothing, and the page would lose
 * the fallback it is entitled to.
 */
export function supportFor(code: string): string {
  return load()[code.toUpperCase()] ? `/support/${encodeURIComponent(code)}.webp` : '';
}

/**
 * Supporting-image urls for a list of album codes, keyed by code.
 *
 * The album page switches albums IN PLACE without navigating, so the component
 * needs every url the rail can reach up front — resolving only the album that
 * was requested would show the band on arrival and never again.
 */
export function supportMapFor(codes: string[]): Record<string, string> {
  const out: Record<string, string> = {};
  for (const code of codes) {
    const url = supportFor(code);
    if (url) out[code] = url;
  }
  return out;
}
