// ============================================================================
// Track-metadata loader (SERVER-ONLY — imports a ~700KB JSON; never import from
// a 'use client' component).
//
// Source: public/music/track-metadata.json, generated by scripts/enrich-tracks.mjs
// (Phase 0). Keyed by songUuid (see lib/ids.ts). Every field is an ESTIMATE
// (est:1) synthesized from genre/mood knowledge bases — the catalog itself has
// no track-level energy/tempo/mood. Swap the generator for audio-DSP later
// without changing this shape. Rule §15: values are precomputed, never inferred
// at query time — this module only reads them.
// ============================================================================
import data from '@/public/music/track-metadata.json';

export interface TrackMeta {
  /** 0–100 energy score (estimated). */
  energy: number;
  /** Tempo in BPM (estimated). */
  tempo: number;
  /** Controlled-vocabulary emotional tags, most-salient first. */
  moods: string[];
  /** Canonical language code (e.g. "en", "ro", "other"). */
  lang: string;
  /** Duration in seconds (estimated; real duration comes from audio at play time). */
  dur: number;
  /** 1 when the values are estimated rather than measured. */
  est: number;
}

interface MetaFile {
  generated: string;
  method: string;
  count: number;
  tracks: Record<string, TrackMeta>;
}

const FILE = data as unknown as MetaFile;
const TRACKS: Record<string, TrackMeta> = FILE.tracks || {};

/** Metadata for a track by its songUuid, or null if unknown (not yet enriched). */
export function getTrackMeta(songId: string): TrackMeta | null {
  return TRACKS[songId] || null;
}

/** True when a track has enrichment metadata (required for theme eligibility). */
export const hasTrackMeta = (songId: string): boolean => !!TRACKS[songId];

export const enrichmentGeneratedAt = (): string => FILE.generated;
export const enrichmentMethod = (): string => FILE.method;
export const enrichmentCount = (): number => FILE.count || Object.keys(TRACKS).length;
